# Generated by Django 3.2.25 on 2024-12-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='Interview_date',
            field=models.DateField(blank=True),
        ),
    ]
